enable entity-specific calculation of inspected points + inspected points score
act3-ace/safe-autonomy-simulation pull request #28
Opened 2024-11-28 00:23 UTC by JohnMcCarroll

closes issue #27

2024-12-12 19:18 UTC, jamie-cunningham approved these changes

2024-12-12 19:21 UTC, jamie-cunningham requested changes
Add unit tests for these methods using the inspector_entity argument

2024-12-17 17:22 UTC, JohnMcCarroll commented
> Add unit tests for these methods using the inspector_entity argument

It looks like there already exist some unit tests to validate the [`get_num_points_inspected`](https://github.com/act3-ace/safe-autonomy-simulation/blob/main/test/sims/inspection/test_inspection_points/test_inspection_point_set.py#L503) and [`get_total_weight_inspected`](https://github.com/act3-ace/safe-autonomy-simulation/blob/main/test/sims/inspection/test_inspection_points/test_inspection_point_set.py#L593) methods when the `inspector_entity` argument is supplied. I ran them locally and they passed.

2025-01-09 19:32 UTC, jamie-cunningham approved these changes

2025-01-09 19:53 UTC, merged