Resolve test case warnings
act3-ace/safe-autonomy-simulation pull request #29
Opened 2024-12-12 20:31 UTC by jamie-cunningham

Resolve test case warnings. These mostly included divide by zero warnings and deprecations.

2024-12-12 20:32 UTC, jamie-cunningham commented
Divide by zero cases were handled in place. Might be worth including a utility function for more robustness. Most cases were unit vector conversions. Open to discussion.

2024-12-13 20:31 UTC, keatincf requested changes
There's also some test warnings due to the name of some classes that start with Test and pytest is picking them up as tests rather

2024-12-16 19:55 UTC, jamie-cunningham commented on safe_autonomy_simulation/sims/inspection/inspection_points.py
> +                    np.linalg.norm(-self.priority_vector) * np.linalg.norm(pos)
Added a manual check

2024-12-16 19:56 UTC, jamie-cunningham commented
> There's also some test warnings due to the name of some classes that start with Test and pytest is picking them up as tests rather

Good catch, I missed those in my test output. I've renamed these classes and resolved the warnings.

2024-12-18 19:36 UTC, keatincf approved these changes

2024-12-18 19:53 UTC, merged